# Generated by Django 4.2.4 on 2023-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_manager', 'Restaurant Manager')], default='customer', max_length=20),
        ),
    ]
