# Generated by Django 4.2.4 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
