# Generated by Django 4.2.4 on 2023-08-14 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfc64505-22b1-4152-92e9-729c350e76da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
