# Generated by Django 4.2.4 on 2023-08-12 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_dish_options_alter_orderdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
