# Generated by Django 4.2.4 on 2023-08-13 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8608da7f-6868-41de-b159-3e430a0f9dcf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
