# Generated by Django 4.2.4 on 2023-08-13 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68dee34a-9e02-49fb-bc8d-0de4e1d056be'), editable=False, primary_key=True, serialize=False),
        ),
    ]
