# Generated by Django 4.2.4 on 2023-08-14 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_dish_updation_date_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a080f3f-a691-46a4-8c72-e3ccc13b2f98'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
